# This workflow builds and tests a Java project using Maven and caches dependencies for improved performance.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ] # Triggers on pushes to the 'main' branch
  pull_request:
    branches: [ "main" ] # Triggers on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Java Development Kit (JDK) version 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Use Temurin distribution
        cache: maven # Cache Maven dependencies

    # Build the project with Maven
    - name: Build with Maven
      run: mvn -B package --file subfolder/pom.xml # -B is for batch mode (no interactive input)

    # Optional: Submit the dependency graph for advanced security insights
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
