name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Navigate to the correct directory before running Maven
    - name: Navigate to project directory
      run: cd "hellocucumber/hellocucumber"

    # List files for debugging (optional)
    - name: List files in the current directory
      run: ls -R

    # Build and Test with Maven
    - name: Build with Maven
      run: mvn clean package -f hellocucumber/hellocucumber/pom.xml -e
